### ISSUE TITLE
A faster topsort

### ISSUE THREAD

**Issue by modulovalue** [simphotonics/directed_graph#6]
Maybe you will find this interesting: https://dart-review.googlesource.com/c/sdk/+/221820

**Comment by simphotonics** [comment]
@modulovalue Thank you for your comment. I had a look at the algorithm. 

This is the adapted version that I investigated and benchmarked:
```Dart
  /// Returns the non-cyclic vertices sorted in topological order.
  ///
  /// If [reachIndexMap] is provided, it is filled with the "reach index" of each vertex.
  /// If [layers] is provided, it is filled with a list of vertices for each
  /// "reach index".
  ///
  /// The "reach index" of a vertex is the length of the longest path that with 
  /// starting point at the vertex. 
  /// For vertices with no neighbors, the index is 0. For any other
  /// vertex, it is 1 plus max of the reach index of its neighbors.
  List<T> topSort({Map<T, int>? reachIndexMap, List<List<T>>? layers}) {
    List<T> unexploredVertices = sortedVertices.toList();
    reachIndexMap ??= {};
    layers ??= <List<T>>[];
    List<T> topologicallySortedVertices = [];
    List<T> previousUnexploredVertices;
    do {
      previousUnexploredVertices = unexploredVertices;
      unexploredVertices = [];
      for (var vertex in previousUnexploredVertices) {
        int reachIndex = 0;
        bool allEdgesExplored = true;
        for (T connectedVertex in edges(vertex)) {
          int? connectedVertexReachIndex = reachIndexMap[connectedVertex];
          if (connectedVertexReachIndex == null) {
            allEdgesExplored = false;
            break;
          } else {
            // print('index: ==========> $reachIndex');
            reachIndex = max(reachIndex, connectedVertexReachIndex + 1);
          }
        }
        if (allEdgesExplored) {
          reachIndexMap[vertex] = reachIndex;
          topologicallySortedVertices.add(vertex);
          if (reachIndex >= layers.length) {
            assert(reachIndex == layers.length);
            layers.add([vertex]);
          } else {
            layers[reachIndex].add(vertex);
          }
        } else {
          unexploredVertices.add(vertex);
        }

        // stdin.readLineSync();
        // print('previousUnexploredVertices: $previousUnexploredVertices');
        // print('unexploredVertices: $unexploredVertices');
        // // print('----');
        // print('reachIndexMap: $reachIndexMap');
        // print('layers: $layers');
        // // print('----');
        // // print('topolSortedVertices: $topologicallySortedVertices');
        // print('===================');
      }
    } while (unexploredVertices.length != previousUnexploredVertices.length);
    return topologicallySortedVertices.reversed.toList();
  }
```
The benchmarks show that `topSort` might be slightly faster than [`topologicalOrdering`](https://pub.dev/documentation/directed_graph/latest/directed_graph/DirectedGraph/topologicalOrdering.html). The benchmark below was obtained by 
sorting a graph with 5632 vertices. As far as I am aware  [`topologicalOrdering`](https://pub.dev/documentation/directed_graph/latest/directed_graph/DirectedGraph/topologicalOrdering.html) is of complexity O(|vertices| + |edges|). 

```Console
 DONE  ./benchmark/bin/directed_graph_benchmark.dart (5 s)
 Manipulating edges:
  ✓ remove vertex l (1 ms)
  ✓ sort edges (8 ms)
 Topology: 5632 vertices
  ✓ isAcyclic (16 ms)
  ✓ graphs.topSort (21 ms)                       <---------------------
  ✓ topologicalOrdering (22 ms)                  <---------------------
  ✓ sortedTopologicalOrdering (95 ms)
```
`topSort` tries to find _leaves_ or vertices without outgoing connections (with reach-index: 0) and then vertices with connections to already processed vertices. The algorithm exits once the lists `previouslyUnexploredVertices` and `unexploredVertices` have the same length. If these lists have the same length but are not empty then a cycle is detected and the iteration terminates. 

The exit condition could be the only disadvantage of `topSort` as an algorithm based on depth-first-search might be faster at detecting cycles. 

Do you have any information if the algorithm was published in a journal? I could add this method but I'd like to cite the source if possible.

**Comment by modulovalue** [comment]
Your adapted version looks a lot like the old version that the PR replaced, could that be?

The new version, that replaced the old one, can also be found here: https://github.com/dart-lang/sdk/blob/2f9d45b8bf9e5843acb94996e193e1a6fdf2da8b/pkg/kernel/lib/util/graph.dart#L151-L210 
I was made aware of it in an issue about Dart compilation times. That link is all I have.

---

Maybe you will find this interesting as well: a repo from almost a decade ago that contains some graph algorithms that directed_graph doesn't have yet.

https://github.com/scribeGriff/graphlab/tree/master/example

**Comment by simphotonics** [comment]
Thanks @modulovalue. Out of curiosity I benchmarked the recursive version of the [alogrithm](https://github.com/dart-lang/sdk/blob/2f9d45b8bf9e5843acb94996e193e1a6fdf2da8b/pkg/kernel/lib/util/graph.dart#L151-L210) you pointed out. It is indeed somewhat faster than the non-recursive version but this is only apparent when sorting large graphs.
