### ISSUE TITLE
Topological ordering strongly connected components

### ISSUE THREAD

**Issue by dcharkes** [simphotonics/directed_graph#7]
I was expecting topological sorting to return a `List<List<T>>` instead of a `Set<T>`.

Current API:

```dart
abstract class DirectedGraphBase<T extends Object> extends Iterable<T> {
  Set<T>? get sortedTopologicalOrdering {
```

For reference:

https://github.com/dart-lang/sdk/blob/main/pkg/kernel/lib/util/graph.dart#L48

```dart
List<List<T>> computeStrongComponents<T>(Graph<T> graph) {
```

Maybe I am misunderstanding how to use this package.

If I have a graph:

- a -> b
- b -> c
- c -> b
- c -> d

I would expect the topological sorting to be: `[[a], [b, c], [d]]`.

**Comment by simphotonics** [comment]
@dcharkes 

Sample usage: 
```Dart
import 'package:directed_graph/directed_graph.dart';

void main() {
  // Constructing a graph from vertices.
  final graph = DirectedGraph<String>(
    {
      'a': {'b'},
      'b': {'c'},
      'c': {'b', 'd'},
    },
  );

  print('Example Directed Graph...');
  print('graph.toString():');
  print(graph);

  print('\nIs Acylic:');
  print(graph.isAcyclic);

  print('\nStrongly connected components:');
  print(graph.stronglyConnectedComponents);

  print('\nSorted Topological Ordering:');
  print(graph.sortedTopologicalOrdering);

  print('\nTopological Ordering:');
  print(graph.topologicalOrdering);

  print('\nCycle:');
  print(graph.cycle);
}
```

Terminal output:
```Term
$ dart example/bin/example.dart 

Example Directed Graph...
graph.toString():
{
 'a': {'b'},
 'b': {'c'},
 'c': {'b', 'd'},
 'd': {},
}

Is Acylic:
false

Strongly connected components:
[[d], [b, c], [a]]

Sorted Topological Ordering:
null

Topological Ordering:
null

Cycle:
[b, c, b]
```

1) What you are looking for are the strongly connected components.  
2) Your graph contains a cycle and as such has no topological ordering. 

Here is an extract from the project documentation section [Terminology](https://github.com/simphotonics/directed_graph#terminology): A topological ordering is an ordered set of all vertices in a graph such that v_i occurs before v_j if there is a directed edge v_i -> v_j.

**Comment by dcharkes** [comment]
Thanks! (I was looking for the wrong term with "topological" in the API.)
