### ISSUE TITLE
breaking change in lazy_memo

### ISSUE THREAD

**Issue by knaeckeKami** [simphotonics/directed_graph#8]
Hello,

the latest release 0.3.9 of directed_graph is not compatible with lazy_memo 0.1.9, since lazy_memo changed LazyMap to be immutable, which breaks the `sortedTopologicalGraph` method.

```dart
    // Get modifiable in-degree map.
    final localInDegreeMap = inDegreeMap;

....

  /// Returns a mapping between vertex and number of
  /// incoming connections.
  late final _inDegreeMap = LazyMap<T, int>(() { ... };

```

However, the version constraints of directed_graph 0.3.9 allow for lazy_memo 0.1.9.

I get that this is the fault of lazy_memo of making breaking changes with a minor release, but it would be great of you could restrict the version constraints so that users of directed graph do not have to hunt this down and add constraints on their own.

Thanks!

**Comment by simphotonics** [comment]
Thanks for filing this issue. Just published version 0.4.0 which is compatible with the latest version of lazy_memo 0.2.2.
