### ISSUE TITLE
Cache is not updated when adding a single edge in a graph

### ISSUE THREAD

**Issue by autumn-chu** [simphotonics/directed_graph#9]
Hi,

Could we update the cache when adding a single edge to a gragh? 

https://github.com/simphotonics/directed_graph/blob/8a10d33f9a644cfbb37b4f8f9448e22edfe13fa6/lib/src/graphs/weighted_directed_graph.dart#L152-L160

Thanks!

**Comment by simphotonics** [comment]
Thanks for submitting this bug report. Since version 0.4.4,  the method `addEdge` includes a call to `updateCache()`.

**Comment by autumn-chu** [comment]
Thanks for your help!
